column_specs:
  course: 'Catalog Nbr'
  country_code: 'Birth Country Code'
  country: 'Birth Country Code'
  year_in_school: 'Acad Level'
  gender: 'Gender'
  crow_id: 'Crow ID'
  institution_code: 'institution'
  term: 'term'
  college: 'College'
  program: 'Major'
  TOEFL_COMPI: 'TOEFL COMPI'
  TOEFL_Listening: 'TOEFL Listening'
  TOEFL_Reading: 'TOEFL Reading'
  TOEFL_Writing: 'TOEFL Writing'
  TOEFL_Speaking: 'TOEFL Speaking'
  IELTS_Overall: 'IELTS Overall'
  IELTS_Listening: 'IELTS Listening'
  IELTS_Reading: 'IELTS Reading'
  IELTS_Writing: 'IELTS Writing'
  IELTS_Speaking: 'IELTS Speaking'
  instructor: 'Instructor Code'
  section: 'Class Section'
  mode: 'mode_of_course'
  length: 'length_of_course'

fixed_expressions:
  course_prefix: 'ENGL'
