column_specs:
  course: 'COURSE_NUMBER'
  country_code: 'NATION_OF_CITIZENSHIP'
  country: 'NATION_OF_CITIZENSHIP_DESC'
  year_in_school: 'STUDENT_CLASS_BOAP_DESC'
  gender: 'GENDER'
  crow_id: 'Crow ID'
  institution_code: 'institution'
  term: 'ACADEMIC_PERIOD_DESC'
  college: 'COLLEGE_DESC'
  program: 'PROGRAM_DESC'
  TOEFL_COMPI: 'TIBT - TOEFL IBT Total Score'
  TOEFL_Listening: 'TIBL - TOEFL IBT Listening Score'
  TOEFL_Reading: 'TIBR - TOEFL IBT Reading Score'
  TOEFL_Writing: 'TIBW - TOEFL IBT Writing Score'
  TOEFL_Speaking: 'TIBS - TOEFL IBT Speaking Score'
  IELTS_Overall: 'ILT2 - IELTS Overall'
  IELTS_Listening: 'ILT1 - IELTS Listening'
  IELTS_Reading: 'ILT3 - IELTS Reading'
  IELTS_Writing: 'ILT5 - IELTS Writing'
  IELTS_Speaking: 'ILT4 - IELTS Speaking'
  instructor: 'Instructor_Code'
  section: 'Class Section'
  mode: 'mode_of_course'
  length: 'length_of_course'

fixed_expressions:
  course_prefix: 'ENGL'
